spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mariadb://localhost:3306/anjeon
    driver-class-name: org.mariadb.jdbc.Driver
    username: tatayeon
    password: 1234
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: Spqowieursakldjfhgx213213dsadDsadsadsASDSAasdsaTRYYUJYDSJHjksahdsdlkjgfh
  expiration_time: 2592000000 # 30일

django:
  api:
    url: "http://localhost:8000/api/upload/"