spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mariadb://rootimpact2.cp8awcg64bme.ap-northeast-2.rds.amazonaws.com/anjeon
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin  # RDS MariaDB 사용자명
    password: xodus0316  # RDS MariaDB 비밀번호
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update  # RDS에서 테이블 자동 업데이트
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: true

jwt:
  secret: Spqowieursakldjfhgx213213dsadDsadsadsASDSAasdsaTRYYUJYDSJHjksahdsdlkjgfh
  expiration_time: 2592000000 # 30일

django:
  api:
    url: "http://localhost:8000/api/upload/"

springdoc:
  swagger-ui:
    path: /api-test

server:
  port: 8080
  ssl:
#    enabled: true
#    key-store: arn:aws:acm:ap-northeast-2:891376917825:certificate/f4b701fc-8d9a-47f8-8fea-24fa6e19b8d1  # 인증서 파일 (p12 또는 jks)
#    key-store-password: your-password
#    key-store-type: PKCS12
