name: Deploy Java App to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for Gradle
      run: chmod +x ../anjeonhaejo/gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: build/libs/

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        # EC2에 JAR 파일 전송
        scp -o StrictHostKeyChecking=no -i /tmp/ssh_key \
          build/libs/*.jar ubuntu@15.165.87.88:/home/ubuntu/app.jar
        
        # EC2에서 애플리케이션 실행 (startup.sh 사용)
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ubuntu@15.165.87.88 << 'EOF'
          chmod +x /home/ubuntu/startup.sh
          /home/ubuntu/startup.sh
        EOF
