name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set execute permissions for gradlew
      run: chmod +x ./gradlew  # 추가된 부분

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build


  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the deployment happens after the build job is completed.
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    # Set up SSH for AWS EC2 deployment
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    - name: Deploy to EC2
      run: |
        # Copy the built JAR file to the EC2 instance
        scp -i /tmp/deploy_key ./build/libs/your-application.jar ubuntu@15.165.87.88:/path/to/deployment/folder
        
        # SSH into EC2 and run the JAR file
        ssh -i /tmp/deploy_key ubuntu@15.165.87.88 << 'EOF'
          cd /path/to/deployment/folder
          java -jar anjeonhaejo.jar
        EOF

